#use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
#ali_source 'alibaba-specs'
#ali_source 'alibaba-specs-mirror'

target 'AliyunContentDetect_Example' do
  pod 'AliyunContentDetect', :path => '../'
  pod 'AFNetworking','3.2.0'
  pod 'Base64nl', '~> 1.2'
  pod 'NSString-Hash'
  pod 'NSString-UrlEncode'
  pod 'CocoaSecurity'
  
  end
target 'AliyunContentDetect_Tests' do
    inherit! :search_paths
  end
