#use_frameworks!
#source 'https://github.com/CocoaPods/Specs.git'
ali_source 'alibaba-specs'
ali_source 'alibaba-specs-mirror'

target 'AliyunContentDetect_Example' do
  pod 'AliyunContentDetect', :path => '../'
  pod 'AFNetworking'
  
  end

  target 'AliyunContentDetect_Tests' do
    inherit! :search_paths

    
  end
